# Copyright (C) 2025 Julian Valentin
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

packages = ["pydantic"]

[files]
"disce/__init__.py" = "./disce/"
"disce/__main__.py" = "./disce/"
"disce/diffs.py" = "./disce/"
"disce/furigana.py" = "./disce/"
"disce/main.py" = "./disce/"
"disce/models/__init__.py" = "./disce/models/"
"disce/models/base.py" = "./disce/models/"
"disce/models/cards.py" = "./disce/models/"
"disce/models/configs.py" = "./disce/models/"
"disce/models/deck_data.py" = "./disce/models/"
"disce/models/deck_metadata.py" = "./disce/models/"
"disce/models/exports.py" = "./disce/models/"
"disce/py.typed" = "./disce/"
"disce/pyscript.py" = "./disce/"
"disce/screens/__init__.py" = "./disce/screens/"
"disce/screens/base.py" = "./disce/screens/"
"disce/screens/decks.py" = "./disce/screens/"
"disce/screens/edit_deck.py" = "./disce/screens/"
"disce/screens/load.py" = "./disce/screens/"
"disce/screens/study.py" = "./disce/screens/"
"disce/storage/__init__.py" = "./disce/storage/"
"disce/storage/base.py" = "./disce/storage/"
"disce/storage/local.py" = "./disce/storage/"
"disce/tools.py" = "./disce/"
